version: '3'
services:
  frontend:
    image: frontend
    build:
      context: ./
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - 8080:80

  backend:
    image: backend
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    restart: always
    depends_on:
      - frontend